[package]
name = "pac-man"
version = "0.1.0"
authors = ["Gregory Langlais <general@gregorylanglais.com>"]
edition = "2018"
description = "AWS Lambda streaming API consumer"
license = "MIT"
readme = "README.md"
repository = "https://github.com/gregl83/pac-man"
homepage = "https://crates.io/crates/pac-man"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
